included:
  - iOS Example
  - ../GenesisSwift
  - ../GenesisSwiftTests

analyzer_rules:
  - unused_declaration
  - unused_import

# some opt_in_rules are disabled, uncomment to activate them gradually
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - legacy_random
  - let_var_whitespace
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - xct_specific_matcher
  - yoda_condition

# tried these below but they don't seem very useful
#  - attributes
#  - discouraged_object_literal
#  - file_header
#  - file_name
#  - legacy_objc_type
#  - nslocalizedstring_key
#  - number_separator
#  - object_literal
#  - sorted_imports
#  - strong_iboutlet
#  - vertical_whitespace_opening_braces

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  allowed_symbols: ["_"]

type_body_length:
    warning: 300
    error: 500

type_name:
    min_length: 1
    max_length: 50

nesting:
  type_level: 2

line_length:
  warning: 150
  error: 200

function_body_length:
  warning: 120
  error: 200

file_length:
  warning: 500
  ignore_comment_only_lines: true

large_tuple:
  warning: 5
  error: 8

cyclomatic_complexity: 15
